In [2]:
import torch

In [4]:
x = torch.empty(5, 3)
x

tensor([[-1.1414e+08,  4.6243e-43, -1.6217e+25],
        [ 4.6243e-43, -1.1012e+08,  4.6243e-43],
        [-2.3185e+10,  4.6243e-43, -1.1414e+08],
        [ 4.6243e-43, -1.6217e+25,  4.6243e-43],
        [-1.1012e+08,  4.6243e-43, -1.6083e+25]])

In [5]:
x = torch.rand(5, 3)
x

tensor([[0.3853, 0.4859, 0.3914],
        [0.1600, 0.6638, 0.0327],
        [0.7805, 0.0824, 0.5025],
        [0.3072, 0.6972, 0.7773],
        [0.2786, 0.4154, 0.5334]])

In [7]:
x = torch.zeros(5, 3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [8]:
x = torch.tensor([5.5, 3])
x

tensor([5.5000, 3.0000])

In [10]:
x = x.new_ones(5, 3, dtype=torch.double)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [11]:
x = torch.randn_like(x, dtype=torch.float)
x

tensor([[-1.7137, -0.3863,  1.1038],
        [-0.3657, -0.6858,  0.5729],
        [ 0.0914,  0.0068, -1.3865],
        [ 0.7433,  0.7548,  1.2976],
        [ 1.1388,  0.6950,  1.5835]])

In [12]:
print(x.size())

torch.Size([5, 3])

In [14]:
y = torch.rand(5, 3)
x + y

tensor([[-1.0181,  0.4459,  1.9968],
        [-0.2348,  0.0766,  0.7622],
        [ 0.8716,  0.7893, -1.0905],
        [ 1.5365,  1.6158,  1.3912],
        [ 1.2046,  1.0188,  1.9267]])

In [16]:
torch.add(x, y)

tensor([[-1.0181,  0.4459,  1.9968],
        [-0.2348,  0.0766,  0.7622],
        [ 0.8716,  0.7893, -1.0905],
        [ 1.5365,  1.6158,  1.3912],
        [ 1.2046,  1.0188,  1.9267]])

In [19]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[-1.0181,  0.4459,  1.9968],
        [-0.2348,  0.0766,  0.7622],
        [ 0.8716,  0.7893, -1.0905],
        [ 1.5365,  1.6158,  1.3912],
        [ 1.2046,  1.0188,  1.9267]])

In [20]:
y.add_(x)

tensor([[-1.0181,  0.4459,  1.9968],
        [-0.2348,  0.0766,  0.7622],
        [ 0.8716,  0.7893, -1.0905],
        [ 1.5365,  1.6158,  1.3912],
        [ 1.2046,  1.0188,  1.9267]])

In [22]:
print(x)
print(x[:, 1
      ])

tensor([[-1.7137, -0.3863,  1.1038],
        [-0.3657, -0.6858,  0.5729],
        [ 0.0914,  0.0068, -1.3865],
        [ 0.7433,  0.7548,  1.2976],
        [ 1.1388,  0.6950,  1.5835]])

tensor([-0.3863, -0.6858,  0.0068,  0.7548,  0.6950])

In [24]:
x = torch.randn(4, 4)
x

tensor([[ 0.7044, -1.1984, -1.3368,  0.1934],
        [-1.1503, -0.9256, -0.9293,  0.2831],
        [-0.0579,  3.1417,  1.9855, -0.8230],
        [ 0.5949, -0.5138, -1.8746, -1.1519]])

In [28]:
if torch.cuda.is_available():
    device = torch.device('cuda')
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x + y
    print(z)
    print(z.to('cpu', torch.double))
    
    

tensor([[ 1.7044, -0.1984, -0.3368,  1.1934],
        [-0.1503,  0.0744,  0.0707,  1.2831],
        [ 0.9421,  4.1417,  2.9855,  0.1770],
        [ 1.5949,  0.4862, -0.8746, -0.1519]], device='cuda:0')

tensor([[ 1.7044, -0.1984, -0.3368,  1.1934],
        [-0.1503,  0.0744,  0.0707,  1.2831],
        [ 0.9421,  4.1417,  2.9855,  0.1770],
        [ 1.5949,  0.4862, -0.8746, -0.1519]], dtype=torch.float64)