In [1]:
import torch


In [3]:
x = torch.ones(2, 2, requires_grad=True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [5]:
y = x + 2 
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [6]:
print(y.grad_fn)

In [8]:
z = y * y * 3
out = z.mean()
print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)

tensor(27., grad_fn=<MeanBackward0>)

In [10]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad_(True))

tensor([[-52.8879,   0.7746],
        [  0.5795,   0.5783]], requires_grad=True)

In [18]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])

In [20]:
x = torch.randn(3, 3)
x

tensor([[ 1.9166, -0.7648,  0.1482],
        [ 1.9736, -0.6327,  0.9644],
        [ 1.8330,  0.2285,  0.5254]])

In [28]:
y = x ** 2
out = y.mean()

In [29]:
print(y, out)

tensor([[3.6732, 0.5849, 0.0220],
        [3.8952, 0.4003, 0.9301],
        [3.3600, 0.0522, 0.2760]])

tensor(1.4660)

In [30]:
print(a.requires_grad)

True

In [31]:
print(x.grad)

None